name: 'Whiplash Heroku Review App Deploy'
description: 'Composite action to help Whiplash review app deployment. It will deploy 2 Review App that has dependency between them. For example a backend API and the UI. '
inputs:
  github_accessToken:  # id of input
    description: 'Github access token'
    required: true
    default: ''
  heroku_apiKey: # id of input
    description: 'Heroku API access token'
    required: true
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/scripts/primary-reviewapp-creation.ps1 -workingDirectoryPath '${{inputs.github_accessToken}}' -herokuApiKey ${{inputs.heroku_apiKey}}
      shell: powershell
