name: 'Whiplash Heroku Generate Review App URLs'
description: 'Composite action that will generate the URLs of the primary and secondary review apps.'
inputs:
  workingDirectoryPath:
    description: 'Default working directory.'
    required: false
    default: ${{github.workspace}}
  github_pullRequestNumber:
    description: 'Pull request number'
    required: false
    default: ${{github.event.number}}
  reviewapp_URL:
    description: 'The URL of the primary Review App'
    required: true
    default: ''
  secondaryReviewapp_URL:
    description: 'The URL of the secondary Review App'
    required: true
    default: ''
  secondaryReviewapp_newBranchPrefix:
    description: 'The prefix to use in the name of the new branch the script will create based on the SecondaryReviewAppGithubSourceBranch. The Secondary Review App will use this new branch as source code.'
    required: true
    default: ''
outputs:
  reviewapp_URL:
    description: "The URL of the primary Review App"
    value: ${{ steps.generate-urls.outputs.reviewapp_URL }}
  secondaryReviewapp_URL:
    description: "The URL of the primary Review App"
    value: ${{ steps.generate-urls.secondaryReviewapp_URL }}
runs:
  using: "composite"
  steps:
    - id: generate-urls
      run: |
        # primary review app
        $url = ${{format('https://{0}-pr-{1}.herokuapp.com', inputs.reviewapp_prefixURL , inputs.github_pullRequestNumber)}}
        echo "reviewapp_URL=$url" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

        # secondary review app
        $url = ${{format('https://{0}-br-{1}{2}.herokuapp.com', inputs.secondaryReviewapp_URL, inputs.secondaryReviewapp_newBranchPrefix, inputs.github_pullRequestNumber)}}
        echo "secondaryReviewapp_URL=$url" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      shell: powershell
