name: 'Whiplash Heroku Generate Review App URLs'
description: 'Composite action that will generate the URLs of the primary and secondary review apps.'
inputs:
  workingDirectoryPath:
    description: 'Default working directory.'
    required: false
    default: ${{github.workspace}}
  github_pullRequestNumber:
    description: 'Pull request number'
    required: false
    default: ${{github.event.number}}
  reviewapp_prefixURL:
    description: 'The URL of the primary Review App'
    required: true
    default: ''
  secondaryReviewapp_prefixURL:
    description: 'The URL of the secondary Review App'
    required: true
    default: ''
  secondaryReviewapp_newBranchPrefix:
    description: 'The prefix to use in the name of the new branch the script will create based on the SecondaryReviewAppGithubSourceBranch. The Secondary Review App will use this new branch as source code.'
    required: true
    default: ''
outputs:
  reviewapp_URL:
    description: "The URL of the primary Review App"
    value: ${{ steps.step1.outputs.reviewapp_URL }}
  secondaryReviewapp_URL:
    description: "The URL of the secondary Review App"
    value: ${{ steps.step2.secondaryReviewapp_URL }}
runs:
  using: "composite"
  steps:
    - id: step1
      shell: pwsh
      run: echo "reviewapp_URL=hello" >> $GITHUB_OUTPUT
    - id: step2
      shell: pwsh
      run: echo "secondaryReviewapp_URL=world" >> $GITHUB_OUTPUT
