name: 'Whiplash Heroku Generate Review App URLs'
description: 'Composite action that will generate the URLs of the primary and secondary review apps.'
inputs:
  github_pullRequestNumber:
    description: 'Pull request number'
    required: false
    default: ${{github.event.number}}
  reviewapp_prefixURL:
    description: 'The URL of the primary Review App'
    required: true
    default: ''
  secondaryReviewapp_prefixURL:
    description: 'The URL of the secondary Review App'
    required: true
    default: ''
  secondaryReviewapp_newBranchPrefix:
    description: 'The prefix to use in the name of the new branch the script will create based on the SecondaryReviewAppGithubSourceBranch. The Secondary Review App will use this new branch as source code.'
    required: true
    default: ''
outputs:
  reviewapp_URL:
    description: "The URL of the primary Review App"
    value: ${{ steps.generate-urls.outputs.reviewapp_URL }}
  secondaryReviewapp_URL:
    description: "The URL of the secondary Review App"
    value: ${{ steps.generate-urls.outputs.secondaryReviewapp_URL }}
runs:
  using: "composite"
  steps:
    - id: generate-urls
      shell: powershell
      run: ${{ github.action_path }}/scripts/main.ps1 `
            -pullRequestNumber '${{inputs.github_pullRequestNumber}}' `
            -reviewappPrefixURL '${{inputs.reviewapp_prefixURL}}' `
            -secondaryReviewappPrefixURL '${{inputs.secondaryReviewapp_prefixURL}}' `
            -secondaryReviewappNewBranchPrefix '${{inputs.secondaryReviewapp_newBranchPrefix}}'

