name: 'Whiplash Heroku Primary Review App Deploy'
description: 'Composite action to help Whiplash review app deployment. It will deploy the primary Review App.'
inputs:
  github-access-key:
    description: 'Github access token'
    required: true
    default: ''
  api-key:
    description: 'Your Heroku API key'
    required: true
    default: ''
  pipeline-name:
    description: 'The name of the pipeline to deploy review app for'
    required: true
    default: ''
  app-name-prefix:
    description: 'The prefix used to generate review app name. This should be the same as what you specified for the review app URL pattern in Heroku Dashboard'
    required: true
    default: ''
  app-environment-values:
    description: 'JSON string with environment values to include in the configuration of the Review APP. (Optional)'
    required: false
    default: ''
  secondary-app-name-prefix:
    description: 'The prefix used to generate the name of the secondary review app. This should be the same as what you specified for the review app URL pattern in Heroku Dashboard'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Generate review app name
      run: |
        echo "APP_NAME=${{inputs.app-name-prefix}}-pr-${{ github.event.number }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        write-output "${{env.APP_NAME}}"
      shell: powershell

    - name: Generate secondary review app name
      run: |
        $tmpBranchName = "${{inputs.app-name-prefix}}pr-${{ github.event.number }}"
        echo "SECONDARY_APP_TMP_BRANCH_NAME=$tmpBranchName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "SECONDARY_APP_NAME=${{inputs.secondary-app-name-prefix}}-br-$tmpBranchName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        write-output "${{env.SECONDARY_APP_TMP_BRANCH_NAME}}"
        write-output "${{env.SECONDARY_APP_NAME}}"
      shell: powershell
