name: 'Whiplash Heroku Review App Deploy'
description: 'Composite action to help Whiplash review app deployment. It will deploy 2 Review App that has dependency between them. For example a backend API and the UI. '
inputs:
  workingDirectoryPath:
    description: 'Default working directory.'
    required: false
    default: ${{github.workspace}}
  github_accessToken:
    description: 'Github access token'
    required: true
    default: ''
  github_repository:
    description: 'The full name of the repository.(owner/repo)'
    required: true
    default: ''
  github_pullRequestNumber:
    description: 'Pull request number'
    required: false
    default: ${{github.event.number}}
  heroku_apiKey:
    description: 'HEROKU API access token'
    required: true
    default: ''
  heroku_pipelineName:
    description: 'The name of the target pipeline in HEROKU'
    required: true
    default: ''
  primaryReviewapp_URL:
    description: 'The URL of the primary Review App'
    required: true
    default: ''
  reviewapp_environmentValues:
    description: 'JSON string with environment values to include in the configuration of the primary Review APP. (Optional)'
    required: false
    default: ''
  reviewapp_URL:
    description: 'The URL of the secondary Review App'
    required: true
    default: ''
  reviewapp_newBranchPrefix:
    description: 'The prefix to use in the name of the new branch the script will create based on the reviewapp_defaultBranch. The Secondary Review App will use this new branch as source code.'
    required: true
    default: ''
  reviewapp_defaultBranch:
    description: 'The name of the branch to use to create the secondary review app.'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - id: create-secondary-reviewapp
      run: ${{ github.action_path }}/scripts/create.ps1 `
              -workingDirectoryPath '${{inputs.workingDirectoryPath}}' `
              -herokuApiKey '${{inputs.heroku_apiKey}}' `
              -herokuPipelineName '${{inputs.heroku_pipelineName}}' `
              -githubAccessToken '${{inputs.github_accessToken}}' `
              -githubRepositoryFullName '${{inputs.github_repository}}' `
              -pullRequestNumber '${{inputs.github_pullRequestNumber}}' `
              -primaryReviewAppURL '${{ inputs.primaryReviewapp_URL }}' `
              -reviewAppURL '${{ inputs.reviewapp_URL }}' `
              -environmentValues '${{inputs.reviewapp_environmentValues}}' `
              -githubDefaultBranch '${{ inputs.reviewapp_defaultBranch }}' `
              -githubNewBranchPrefix '${{inputs.reviewapp_newBranchPrefix}}'
      shell: powershell
